# TrajectoryPlannerROS:
#   holonomic_robot: false
#   max_vel_x: 15.0
#   min_vel_x: 0.0
#   max_vel_theta: 0.5
#   min_in_place_vel_theta: 0.01
#   acc_lim_x: 5.0
#   acc_lim_y: 0.0
#   acc_lim_theta: 1.0
#   xy_goal_tolerance: 5.0
#   yaw_goal_tolerance: 3.14

DWAPlannerROS:
  holonomic_robot: false
  acc_lim_x: 5.0
  acc_lim_trans: 5.0
  acc_lim_y: 1.0
  acc_lim_theta: 1.0
  max_vel_trans: 15.0
  min_vel_trans: 0.1
  max_vel_x: 15.0
  min_vel_x: -10.0
  max_vel_y: 0
  min_vel_y: 0
  max_vel_theta: 0.2
  min_vel_theta: 0.0
  max_rot_vel: 0.2
  min_rot_vel: 0.0
  xy_goal_tolerance: 5.0
  yaw_goal_tolerance: 1.5

TebLocalPlannerROS:
  acc_lim_x: 10.0
  acc_lim_y: 0.1
  acc_lim_theta: 0.5
  max_vel_x: 10.0
  min_vel_x_backwards: 3.0
  max_vel_y: 0
  max_vel_theta: 0.2
  min_turning_radius: 0.0
  footprint_model:
    type: "two_circles"
    front_offset: 3.0
    front_radius: 3.0
    rear_offset: 3.0
    rear_radius: 3.0
  xy_goal_tolerance: 5.0
  yaw_goal_tolerance: 0.5
  costmap_obstacles_behind_robot_dist: 12
  max_global_plan_lookahead_dist: 6
  inflation_dist: 0
  min_obstacle_dist: 0
  dt_ref: 0.5
  dt_hysteresis: 0.1
  